known_person = [
    "I",
    "everyone",
    "mashaal",
    "priyansh",
    "anmol",
    "divyansh",
    "rupesh",
    "rajesh",
    "ashutosh",
    "naveen",
    "harshit",
    "aswin",
    "herschelle",
]


known_objects = ["messsage", "schedule", "inventory", "funds", "list"]


functionality_space = {
    "add reminder": "ADD MESSAGE",
    "add message": "ADD MESSAGE",
    "tell": "ADD MESSAGE",
    "drop message": "ADD MESSAGE",
    "remind": "ADD MESSAGE",
    "leave message": "ADD MESSAGE",
    "send message": "SEND MESSAGE",
    "have message": "GET MESSAGE",
    "get message": "GET MESSAGE",
    "add": "ADD",
    "create list": "CREATE LIST",
    "add event": "ADD TO SCHEDULE",
    "schedule event": "ADD TO SCHEDULE",
    "get event": "GET SCHEDULE",
    "get events": "GET SCHEDULE",
    "check schedule": "GET SCHEDULE",
    "get schedule": "GET SCHEDULE",
    "add fund": "ADD FUND",
    "add expense": "REMOVE FUND",
    "remove fund": "REMOVE FUND",
    "spend": "REMOVE FUND",
    "assign task": "ADD TASK",
    "remove task": "REMOVE TASK",
    "update task": "UPDATE TASK",
    "add task": "ADD TASK",
    "add inventory": "ADD INVENTORY",
    "remove inventory": "REMOVE INVENTORY",
    "other": "OTHER",
}
